const ROLES = {
  ADMIN: 'ADMIN',
  ENGINEERING: 'ENGINEERING',
  CONTROLLER: 'CONTROLLER',
  MANAGEMENT: 'MANAGEMENT',
  CONTRACTOR: 'CONTRACTOR',
  VISUALIZER: 'VISUALIZER',
  FOREMAN: 'FOREMAN',
};

const TASK_STATUS = {
  PLANNED: 'PLANNED',
  RETRABALHO: 'RETRABALHO',
  RESERVA: 'RESERVA',
  IN_PROGRESS: 'IN_PROGRESS',
  EXECUTED: 'EXECUTED',
  CANCELLED: 'CANCELLED',
};

const FEEDBACK_STATUS = {
  EXECUTED: 'EXECUTED',
  STARTED: 'STARTED',
  NOT_STARTED: 'NOT_STARTED',
  CANCELLED: 'CANCELLED',
};

const WEEK_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
};

module.exports = {
  ROLES,
  TASK_STATUS,
  FEEDBACK_STATUS,
  WEEK_STATUS,
};
